name="             Alejandro            "
print (type (name))
print (name [0])
print (name [1])
print (name [2])
print (name [3])
print (name [4])
print (name [5])
print (name [6])
print (name [7])
print (name [8])
last_name="Caicedo"
print (name*5)
print (len (name))
print(name.lower())
print(name.upper())
print(name.strip())
print(name + " " + last_name)